In [1]:
%reload_ext autoreload
%autoreload 2

from forbiddenfruit import curse
import numpy as np

def push_back(self, a):
    self.append(a)
#list.push_back = push_back

def push_back(self, a):
    self.insert(0,a)
    
curse(list, "push_back", push_back)


# DTW each stroke iteratively
# DTW until stroke+1 is chosen
    # stroke + i is the min of stroke/reverse stroke
    # check whether the stroke or reverse stroke does better
INFINITY = 1000

def euclidean_distance(a, b):
    d = 0
    a = np.asarray([a])
    b = np.asarray([b])
    #print(a.shape,b)
    for i in range(a.shape[0]):
        tmp = a[i] - b[i]
        d += tmp * tmp
    return np.sqrt(d)

def d_argmin(a, b, c):
    if a <= b and a <= c:
        return 0
    elif b <= c:
        return 1
    else:
        return 2

def d_min(a, b, c):
    if a < b and a < c:
        return a
    elif b < c:
        return b
    else:
        return c

def refill_cost_matrix(a, b, cost_mat, start_a, end_a, start_b, end_b, constraint, dist_func=euclidean_distance):
    # Include some buffer beyond just the strokes being flipped
    # To get improvement, compare the cost at this point before and after
    #cost_mat = np.empty((a.shape[0] + 1, b.shape[0] + 1), dtype=np.float64)
    #cost_mat[:] = INFINITY
    #cost_mat[0, 0] = 0
    for i in range(start_a+1, end_a+1):
        for j in range(max(start_b+1, i-constraint), min(end_b+1, i+constraint+1)):
            cost_mat[i, j] = dist_func(a[i - 1], b[j - 1]) +\
                d_min(cost_mat[i - 1, j], cost_mat[i, j - 1], cost_mat[i - 1, j - 1])

    return cost_mat[1:, 1:]


def traceback_partial(cost_mat, ilen, jlen, )

def create_cost_mat_2d(a,b,constraint, dist_func=euclidean_distance):
    cost_mat = np.empty((a.shape[0] + 1, b.shape[0] + 1), dtype=np.float64)
    cost_mat[:] = INFINITY
    cost_mat[0, 0] = 0
    for i in range(1, cost_mat.shape[0]):
        for j in range(max(1, i-constraint), min(cost_mat.shape[1], i+constraint+1)):
            cost_mat[i, j] = dist_func(a[i - 1], b[j - 1]) +\
                d_min(cost_mat[i - 1, j], cost_mat[i, j - 1], cost_mat[i - 1, j - 1])

    return cost_mat[1:, 1:]
    
def traceback(cost_mat, ilen, jlen):
    cost = 0.0
    i = ilen - 1
    j = jlen - 1
#     cdef vector[int] a
#     cdef vector[int] b
#     a.push_back(i)
#     b.push_back(j)

    a = []
    b = []
    a.append(i)
    b.append(j)
    #cdef int match
    while (i > 0 or j > 0):
        match = d_argmin(cost_mat[i - 1, j - 1], cost_mat[i - 1, j], cost_mat[i, j - 1])
        if match == 0:
            i -= 1
            j -= 1
            cost += cost_mat[i - 1, j - 1]
        elif match == 1:
            i -= 1
            cost += cost_mat[i - 1, j]
        else:
            j -= 1
            cost += cost_mat[i, j - 1]
        a.push_back(i)
        b.push_back(j)
    return a, b, cost


np.set_printoptions(suppress=True)
    
x1 = np.array([1,2.0,3])
x2 = np.array([1,1.2,3])
mat = create_cost_mat_2d(x1,x2,constraint=5)
r = traceback(mat, x1.shape[0], x2.shape[0])
print(r)

if False:
    x1 = np.array([1,2.9,2.9,3])
    x2 = np.array([1.1,1.2,1.4,3])
    mat = create_cost_mat_2d(x1,x2,constraint=5)
    print(mat)
    traceback(mat, x1.shape[0], x2.shape[0])

# [0 0 0 1 2 3]
# [0 1 2 3 3 3]



([0, 1, 2], [0, 1, 2], 0.8)


In [2]:
def d_min(a, b, c):
    if a < b and a < c:
        return a
    elif b < c:
        return b
    else:
        return c


In [3]:
from pydtw import *
# from taylor_dtw.custom_dtw import *

x1 = np.array([1,2.9,2.9,3,5,6,7,8])
x2 = np.array([1.1,1.2])

x = constrained_dtw1d(x2,x1,2)
print(x)
x = constrained_dtw1d(x1,x2,2)
print(x)
x = dtw1d(x2,x1)
print(x)
x = dtw1d(x1,x2)
print(x)


mat = create_cost_mat_2d(x1,x2,constraint=5)
print(mat)
print(traceback(mat, len(x1), len(x2)))
mat = create_cost_mat_2d(x2,x1,constraint=5)
print(mat)
print(traceback(mat, len(x2), len(x1)))

(<MemoryView of 'ndarray' at 0x7f35705f76c0>, 26.5, [0, 1, 1, 1, 1, 1, 1, 1], [0, 1, 2, 3, 4, 5, 6, 7])
(<MemoryView of 'ndarray' at 0x7f35705f7860>, 26.5, [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 1, 1, 1, 1, 1, 1])
(<MemoryView of 'ndarray' at 0x7f35705f76c0>, 26.5, [0, 1, 1, 1, 1, 1, 1, 1], [0, 1, 2, 3, 4, 5, 6, 7])
(<MemoryView of 'ndarray' at 0x7f35705f7860>, 26.5, [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 1, 1, 1, 1, 1, 1])
[[   0.1    0.3]
 [   1.9    1.8]
 [   3.7    3.5]
 [   5.6    5.3]
 [   9.5    9.1]
 [  14.4   13.9]
 [1000.    19.7]
 [1000.  1000. ]]
([0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 1, 1, 1, 1, 1, 1], 1033.9)
[[   0.1    1.9    3.7    5.6    9.5   14.4 1000.  1000. ]
 [   0.3    1.8    3.5    5.3    9.1   13.9   19.7 1000. ]]
([0, 1, 1, 1, 1, 1, 1, 1], [0, 1, 2, 3, 4, 5, 6, 7], 1033.9)


<ipython-input-3-204019ece499>:7: UserWarning: Constraint 2 too small for sequences length 2 and 8; using 7
  x = constrained_dtw1d(x2,x1,2)
<ipython-input-3-204019ece499>:9: UserWarning: Constraint 2 too small for sequences length 8 and 2; using 7
  x = constrained_dtw1d(x1,x2,2)


In [4]:
x1 = np.array([1,2.9,2.9,3])
x2 = np.array([1.1,1.2,1.4,3])
mat = create_cost_mat_2d(x1,x2,constraint=50000000)
print(mat)


[[0.1 0.3 0.7 2.7]
 [1.9 1.8 1.8 0.8]
 [3.7 3.5 3.3 0.9]
 [5.6 5.3 4.9 0.9]]


In [5]:
import numpy as np
#from pydtw import *
x1 = np.array([1,2.9,2.9,3])
x2 = np.array([1.1,1.2,1.4,3])

#constrained_dtw1d(x1,x2,10)
f, cost, a, b = dtw1d(x1,x2)
print(np.sum(np.abs(x1[a]-x2[b])), cost)
print(a, b)
print(np.asarray(f))

1.9000000000000001 1.9000000000000001
[0, 0, 1, 2, 3] [0, 1, 2, 3, 3]
[[0.1 0.3 inf inf]
 [1.9 1.8 1.8 inf]
 [inf 3.5 3.3 1.9]
 [inf inf 4.9 1.9]]


In [6]:
x1 = np.array([1,2.0,3])
x2 = np.array([1,1.2,3])
mat = create_cost_mat_2d(x1,x2, constraint=10)
dist, cost, a, b = dtw1d(x1, x2, )
print(mat)

[[0.  0.2 2.2]
 [1.  0.8 1.2]
 [3.  2.6 0.8]]


In [7]:
%reload_ext autoreload
%autoreload 2

import sys
sys.path.append("../../")
sys.path.append("../")
sys.path.append("/media/data/GitHub/simple_hwr")
import os
import numpy as np
from hwr_utils import *
from hwr_utils.stroke_plotting import *
from hwr_utils.stroke_recovery import get_number_of_stroke_pts_from_gt
from hwr_utils.stroke_recovery import *
import json
from matplotlib import pyplot as plt

In [128]:
def process(gt, gt_next, pred, str_len, window_size=window):
    """ Match the GT stroke + a few more strokes
        Get last match to GT stroke
        
        
        gt_next: next stroke
    """
    _comb = np.concatenate([gt, gt_next], axis=0)
    #print("combined", _comb, pred)
    f, costr, a, b = constrained_dtw1d(_comb,pred, window_size)
    #print(a,b)
    #print("GT", _comb[a])
    #print("Pred", pred[b])
    dist = np.sum(abs(_comb[a]-pred[b]))
    return dist, a, b
    


def DTW(gt, preds,window=5):
    gt_1d = gt[:,0].copy(order='C')
    preds_1d = preds[:,0].copy(order='C')

    gt_stroke_lens = get_number_of_stroke_pts_from_gt(gt, stroke_numbers=False)
    gt_stroke_lens = np.insert(gt_stroke_lens,0,0) # possibly swap first stroke

    match_a = []
    match_b = []
    # Cython Function that takes exisiting distance matrix and only fills out the last bit

    pos_gt = 0
    pos_pred = 0

    ## FIRST ATTEMPT AT MANUAL DTW MATCH
    for i in range(len(gt_stroke_lens)):
        next_stroke_length = gt_stroke_lens[i+1] if i+1<len(gt_stroke_lens) else 0
        str_len = gt_stroke_lens[i]
        temp_window = min(window, next_stroke_length)

        end_gt, end_pred = pos_gt+str_len, pos_pred+str_len+temp_window
        gt_next = gt_1d[end_gt:end_gt+next_stroke_length]
        gt_stroke = gt_1d[pos_gt:end_gt]
        pred_stroke = preds_1d[pos_pred:end_pred]    
        #print(gt_stroke, gt_next, pred_stroke)
        dist,a,b = process(gt_stroke,gt_next[:temp_window],pred_stroke,str_len,window)  
        

        if i < len(gt_stroke_lens)-1:
            gtr_next=gt_next[::-1][:temp_window].copy(order='C')
            distr,ar,br = process(gt_stroke,gtr_next,pred_stroke,str_len,temp_window)   
            # Invert the next stroke
            #print("LOSS", dist, distr)
            if distr<dist:
                #print("REVERSE REVERSE!")
                gt_1d[end_gt:end_gt+next_stroke_length] = gtr_next
                a,b = ar, br

            #print("A", a)
            #print("B", b)



            if i>0: # first one doesn't save alignment
                last_stroke_idx_a = len(a) - 1 - np.argmax(a[::-1]==str_len) # how far to go in the alignment list
                # -1 because 0 indexing; 10 - np.argmax(np.array([5]*10)[::-1]==5) - 1
                #print("How far to go in alignment list", last_stroke_idx_a)
                pos_pred_update = b[last_stroke_idx_a] # how far the pred matches
                #print("How far the pred matches", pos_pred_update)
                #print("How far the gt matches (by def)", str_len)

                match_a += [x+pos_gt   for x in   a[:last_stroke_idx_a]]
                match_b += [x+pos_pred for x in b[:last_stroke_idx_a]]
                pos_gt += str_len
                pos_pred += pos_pred_update
        else:
            match_a += [x+pos_gt   for x in a]
            match_b += [x+pos_pred for x in b]

#         print("MATCH A:", match_a)
#         print("MATCH B:", match_b)
#         print("NEW POS:", pos_gt, pos_pred)
#     print(gt_1d)


In [129]:
gt = np.array(range(36)).reshape(9,4).astype(np.float64)
gt[:,2] = [1,0,0,1,0,1,1,0,0]
preds = [[8, 9, 1, 3], [4, 5, 0, 7], [0, 1, 0, 11], [12, 13, 1, 15], [16, 17, 0, 19], [20, 21, 1, 23], [32, 33, 1, 27], [28, 29, 0, 31], [24, 25, 0, 35]]
preds = [[8, 9, 1, 3], [4, 5, 0, 7], [0, 1, 0, 11], [12, 13, 1, 15], [16, 17, 0, 19], [20, 21, 1, 23], [21, 21, 1, 23], [32, 33, 1, 27], [28, 29, 0, 31], [24, 25, 0, 35]]
preds = np.asarray(preds).astype(np.float64)

pos_gt = 0
pos_pred = 0

print(gt)
print(gt_stroke_lens)
print(preds)

DTW(gt, preds, window = 5)

[[ 0.  1.  1.  3.]
 [ 4.  5.  0.  7.]
 [ 8.  9.  0. 11.]
 [12. 13.  1. 15.]
 [16. 17.  0. 19.]
 [20. 21.  1. 23.]
 [24. 25.  1. 27.]
 [28. 29.  0. 31.]
 [32. 33.  0. 35.]]
[0 3 2 1 3]
[[ 8.  9.  1.  3.]
 [ 4.  5.  0.  7.]
 [ 0.  1.  0. 11.]
 [12. 13.  1. 15.]
 [16. 17.  0. 19.]
 [20. 21.  1. 23.]
 [21. 21.  1. 23.]
 [32. 33.  1. 27.]
 [28. 29.  0. 31.]
 [24. 25.  0. 35.]]


In [10]:
def find_worst_strokes(gt, pred, a, b):

    
    
f, cost, a, b = constrained_dtw1d(gt,pred, window=20)


IndentationError: expected an indented block (<ipython-input-10-7418267b8e6d>, line 5)

In [ ]:
import numpy as np
from matplotlib import pyplot as plt
max_width = 8

t = []
for i in range(10000):
    #x = min(max(int(abs(np.random.exponential()) * (max_width) * .2 + 2), 1), max_width)
    x = min(max(int(abs(np.random.randn()) * (max_width - 1) * .5 + 1), 1),max_width)
    #x = min(max(int(abs(np.random.beta(2,5)) * max_width + 1), 1),max_width)

    t.append(x)

plt.hist(t)

In [ ]:
import numpy as np
from matplotlib import pyplot as plt
max_width = 8

t = []
for i in range(10000):
    #x = min(max(int(abs(np.random.exponential()) * (max_width) * .2 + 2), 1), max_width)
    #x = min(max(int(abs(np.random.randn()) * (max_width - 1) * .5 + 1), 1),max_width)
    x = min(max(int(abs(np.random.beta(2,4)) * max_width + .8), 1),max_width)

    t.append(x)

plt.hist(t)

9