In [1]:
%reload_ext autoreload
%autoreload 2

import sys
sys.path.append("../..")

import os
import tempfile
from pathlib import Path
import numpy as np
from torch.utils.data import DataLoader
from models.basic import CNN, BidirectionalRNN
from torch import nn
from models.stroke_recovery_loss import StrokeLoss
import torch
from models.CoordConv import CoordConv
from trainers import TrainerStrokeRecovery
from hwr_utils.stroke_dataset import StrokeRecoveryDataset, read_img
from hwr_utils.stroke_recovery import *
from hwr_utils import utils
from torch.optim import lr_scheduler
from timeit import default_timer as timer
from train_stroke_recovery import graph

folder = Path("online_coordinate_data/3_stroke_vSmall")
folder = Path("online_coordinate_data/8_stroke_vSmall_16")
folder = Path("online_coordinate_data/MAX_stroke_vTEST_AUGMENTFull")

print(os.getcwd())
x_relative_positions = True
test_size = 5
train_size = None
batch_size=32

test_dataset=StrokeRecoveryDataset([folder / "test_online_coords.json"],
                        img_height = 60,
                        num_of_channels = 1.,
                        max_images_to_load = test_size,
                        root=r"../../data",
                        x_relative_positions=x_relative_positions
                        )

test_dataloader = DataLoader(test_dataset,
                              batch_size=batch_size,
                              shuffle=True,
                              num_workers=3,
                              collate_fn=test_dataset.collate,
                              pin_memory=False)

device="cuda"
example = next(iter(test_dataloader)) # BATCH, WIDTH, VOCAB
output = Path("./TEST_GRAPHING")

# This graphs the directions etc.
# graph(example, save_folder=output, x_relative_positions=x_relative_positions)

fd, path = tempfile.mkstemp()
try:
    draw_strokes(normalize_stroke_list(example.raw), ratio, save_path=path, line_width=.8)
    img = read_img(path)
finally:
    os.remove(path)

print(img)


ModuleNotFoundError: No module named 'robust_loss_pytorch'

In [4]:
print(example.keys())

dict_keys(['line_imgs', 'gt', 'gt_list', 'x_relative', 'label_lengths', 'paths', 'x_func', 'y_func', 'start_times'])


In [10]:
print(example["gt"].shape)

torch.Size([5, 869, 4])


In [ ]:
np.r_(start_indices, end_indices)

In [ ]:
array = np.array([1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0])
start_indices = np.where(array)[0]
start_point_ct = len(start_indices)
total_point_ct = len(array)
end_indices = np.append((start_indices-1)[1:], total_point_ct-1)

xs = np.array(range(0, total_point_ct))*1.5
x = np.interp(xs, np.append(start_indices*1.0, end_indices), np.append(np.ones(start_point_ct), np.zeros(start_point_ct)))

print(x, xs, np.append(start_indices*1.0, end_indices))

In [ ]:
array = np.array([1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0])
start_indices = np.where(array)[0]
start_point_ct = len(start_indices)
total_point_ct = len(array)
xs = np.repeat(start_indices,2)
xs[::2] -= 1
xs = np.append(xs[1:], total_point_ct)
ys = np.zeros(2*start_point_ct)
ys[1::2] += 1
print(xs, ys)

# make it distance traveled!

interp_xs = np.array(range(0, total_point_ct))
out = np.interp(interp_xs, xs, ys)
print(out)

In [ ]:
x = np.array([1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0])
start_indices = np.where(x)
#end_indices = start_indices-1

print(start_indices)

In [ ]:
m = np.array([1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0])
np.append(m, 599, 5)

TypeError: 'RClass' object is not callable

In [61]:
array = np.array([1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0])
start_indices = np.where(array)[0]
start_point_ct = len(start_indices)
total_point_ct = len(array)
end_indices = np.append((start_indices-1)[1:], total_point_ct)

xs = np.array(range(0, total_point_ct))*1.5
x = np.interp(xs, np.append(start_indices*1.0, end_indices), np.append(np.ones(start_point_ct), np.zeros(start_point_ct)))

print(x, xs, np.append(start_indices*1.0, end_indices))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.] [ 0.   1.5  3.   4.5  6.   7.5  9.  10.5 12.  13.5 15.  16.5 18.  19.5
 21.  22.5 24. ] [ 0.  8. 14.  7. 13. 17.]


In [79]:
array = np.array([1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0])
start_indices = np.where(array)[0]
start_point_ct = len(start_indices)
total_point_ct = len(array)
xs = np.repeat(start_indices,2)
xs[::2] -= 1
xs = np.append(xs[1:], total_point_ct)
ys = np.zeros(2*start_point_ct)
ys[1::2] += 1
print(xs, ys)

# make it distance traveled!

interp_xs = np.array(range(0, total_point_ct))
out = np.interp(interp_xs, xs, ys)
print(out)

[ 0  7  8 13 14 17] [0. 1. 0. 1. 0. 1.]
[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.         0.         0.2        0.4        0.6
 0.8        1.         0.         0.33333333 0.66666667]


In [ ]:
x = np.array([1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0])
start_indices = np.where(x)
#end_indices = start_indices-1

print(start_indices)

In [36]:
m = np.array([1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0])
np.append(m, 599, 5)

IndexError: index 599 is out of bounds for axis 0 with size 17

In [27]:
import numpy as np
def calc_distance(x,y):
    return ((x[:-1] - x[1:])**2+(y[:-1] - y[1:])**2)**(1/2)

def calc_stroke_distances(x,y,start_strokes):
    [start_indices] = np.where(m)
    total_point_ct = len(start_strokes)
    end_indices = np.append((start_indices-1)[1:], total_point_ct-2) # one because legnth is +1, one because length is shortened after calculating distance
    distances = calc_distance(x,y)
    cum_sum = np.cumsum(distances)
    lengths = cum_sum[end_indices]
    return lengths

x = np.array(range(0,17))#**2
y = np.array(range(0,17))#**2
m = np.array([1,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0])
calc_stroke_distances(x,y,m)

array([ 4.24264069, 11.3137085 , 19.79898987, 22.627417  ])

In [32]:
start_points = np.array([1,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0])
start_indices = np.where(start_points)[0]
start_point_ct = len(start_indices)
total_point_ct = len(start_points)

# Create list of start and end points (x's for interpolation)
xs = np.repeat(start_indices,2)
xs[::2] -= 1
xs = np.append(xs[1:], total_point_ct)

## Create y's for interpolation (the target values)
ys = np.zeros(2*start_point_ct)

# Make each stroke length 1
#ys[1::2] += 1

# Make each target the actual stroke length
distances = calc_stroke_distances(x,y, start_points)
ys[1::2] = distances
print(xs, ys)

interp_xs = np.array(range(0, total_point_ct))
out = np.interp(interp_xs, xs, ys)
print(out)

[ 0  2  3  7  8 13 14 17] [ 0.          4.24264069  0.         11.3137085   0.         19.79898987
  0.         22.627417  ]
[ 0.          2.12132034  4.24264069  0.          2.82842712  5.65685425
  8.48528137 11.3137085   0.          3.95979797  7.91959595 11.87939392
 15.8391919  19.79898987  0.          7.54247233 15.08494467]


In [33]:
len([1,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0])

17

In [35]:
np.fromstring("""[0.         1.41421356 2.82842712 0.         1.41421356 2.82842712, 4.24264069 5.65685425 0.
                               1.41421356 2.82842712 4.24264069 5.65685425 7.07106781 0.         1.41421356 2.82842712]""")

<ipython-input-35-94f2b4b76aa7>:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring("""[0.         1.41421356 2.82842712 0.         1.41421356 2.82842712, 4.24264069 5.65685425 0.


ValueError: string size must be a multiple of element size

In [43]:
from ast import literal_eval
import numpy as np
import re 
a = """[0.,         1.41421356 2.82842712 0.         1.41421356 2.82842712 4.24264069 5.65685425 0.  1.41421356 2.82842712 4.24264069 5.65685425 7.07106781 0.         1.41421356 2.82842712]"""
def to_numpy(array_string):
    from ast import literal_eval
    import numpy as np
    import re
    array_string = re.sub('\s+', ',', array_string)
    array_string = np.array(literal_eval(array_string))
    return array_string
to_numpy(a)

SyntaxError: invalid syntax (<unknown>, line 1)

In [50]:
print(m)
print(m[slice(5,None)])

[1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0]
[0 0 0 1 0 0 0 0 0 1 0 0]


In [56]:
import pytz
import datetime
MYTIMEZONE = pytz.timezone('US/Mountain')

start_time = datetime.datetime.today().replace(tzinfo=MYTIMEZONE).isoformat()
print(start_time)

2020-01-18T12:17:04.781716-07:00


In [57]:
{'Description': 'https://nhmu.utah.edu/free-days-nhmu\nAlways free:\nUtah Museum of Fine Arts : Free with EBT\nClark Planetarium : Always Free; 110 400 W, Salt Lake City, UT\nHill Aerospace Museum : Always Free; (Ogden) 7961 Wardleigh Rd, Hill AFB, UT 84056\nThanksgiving Point : $2 per person, up to six people, with EBT', 'Subject': 'Natural History Museum of Utah', 'Start Date': '03/03/2020', 'End Date': '03/03/2020', 'Start Time': 0.4166666666666667}

{'Description': 'https://nhmu.utah.edu/free-days-nhmu\nAlways free:\nUtah Museum of Fine Arts : Free with EBT\nClark Planetarium : Always Free; 110 400 W, Salt Lake City, UT\nHill Aerospace Museum : Always Free; (Ogden) 7961 Wardleigh Rd, Hill AFB, UT 84056\nThanksgiving Point : $2 per person, up to six people, with EBT',
 'Subject': 'Natural History Museum of Utah',
 'Start Date': '03/03/2020',
 'End Date': '03/03/2020',
 'Start Time': 0.4166666666666667}

In [61]:
datetime.time(.4*24)

TypeError: integer argument expected, got float

In [60]:
datetime.time(.4)

datetime.time(4, 0)

In [64]:
def time_from_decimal_hrs(hrs):
    hours = int(hrs)
    minutes = int((hrs*60) % 60)
    seconds = int((hrs*3600) % 60)
    return datetime.time(hours, minutes, seconds)
time_from_decimal_hrs(19.4)


19 24 0


datetime.time(19, 24)

In [65]:
datetime.datetime.now().time()

datetime.time(13, 16, 11, 649479)

In [82]:
from pathlib import Path
Path.__add__ = lambda self, rhs: Path(self.parent / "{}{}".format(self.stem,rhs)).with_suffix(self.suffix)

x = Path("/media/my.csv")
x + "raw"


PosixPath('/media/myraw.csv')

In [85]:
from collections import OrderedDict
x = [OrderedDict([('Subject', 'Tracy Aviary'), ('Date', 43501), ('Time', ''), ('Info', ''), ('Location', '')]), OrderedDict([('Subject', 'Utah Museum of Fine Arts'), ('Date', 'Always'), ('Time', ''), ('Info', 'Free with EBT'), ('Location', '')]), OrderedDict([('Subject', 'Natural History Museum of Utah (GET TICKETS!)'), ('Date', 43893), ('Time', 0.4166666666666667), ('Info', 'https://nhmu.utah.edu/free-days-nhmu'), ('Location', '301 Wakara Way, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Natural History Museum of Utah (GET TICKETS!)'), ('Date', 43984), ('Time', 0.4166666666666667), ('Info', 'https://nhmu.utah.edu/free-days-nhmu'), ('Location', '301 Wakara Way, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Natural History Museum of Utah (GET TICKETS!)'), ('Date', 44075), ('Time', 0.4166666666666667), ('Info', 'https://nhmu.utah.edu/free-days-nhmu'), ('Location', '301 Wakara Way, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Butte Garden'), ('Date', 43945), ('Time', ''), ('Info', ''), ('Location', '300 Wakara Way, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Butte Garden'), ('Date', 44036), ('Time', ''), ('Info', ''), ('Location', '300 Wakara Way, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Butte Garden'), ('Date', 44081), ('Time', ''), ('Info', ''), ('Location', '300 Wakara Way, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Butte Garden'), ('Date', 44109), ('Time', ''), ('Info', ''), ('Location', '300 Wakara Way, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Butte Garden'), ('Date', 44170), ('Time', ''), ('Info', ''), ('Location', '300 Wakara Way, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Butte Garden'), ('Date', 44171), ('Time', ''), ('Info', ''), ('Location', '300 Wakara Way, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Clark Planetarium'), ('Date', 'Always'), ('Time', ''), ('Info', 'Always Free; 110 400 W, Salt Lake City, UT'), ('Location', '')]), OrderedDict([('Subject', 'Free National Parks'), ('Date', 43850), ('Time', ''), ('Info', ''), ('Location', '')]), OrderedDict([('Subject', 'Free National Parks'), ('Date', 43939), ('Time', ''), ('Info', ''), ('Location', '')]), OrderedDict([('Subject', 'Free National Parks'), ('Date', 44068), ('Time', ''), ('Info', ''), ('Location', '')]), OrderedDict([('Subject', 'Free National Parks'), ('Date', 44100), ('Time', ''), ('Info', ''), ('Location', '')]), OrderedDict([('Subject', 'Free National Parks'), ('Date', 44146), ('Time', ''), ('Info', ''), ('Location', '')]), OrderedDict([('Subject', 'Hill Aerospace Museum'), ('Date', 'Always'), ('Time', ''), ('Info', 'Always Free; (Ogden) 7961 Wardleigh Rd, Hill AFB, UT 84056'), ('Location', '')]), OrderedDict([('Subject', 'Scales and Tails'), ('Date', 'Always'), ('Time', ''), ('Info', 'Free with POAP'), ('Location', '')]), OrderedDict([('Subject', 'Hogle Zoo?'), ('Date', 44139), ('Time', ''), ('Info', 'Unconfirmed'), ('Location', '2600 Sunnyside Ave S, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Hogle Zoo?'), ('Date', 44146), ('Time', ''), ('Info', 'Unconfirmed'), ('Location', '2600 Sunnyside Ave S, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Hogle Zoo?'), ('Date', 44153), ('Time', ''), ('Info', 'Unconfirmed'), ('Location', '2600 Sunnyside Ave S, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Hogle Zoo?'), ('Date', 44160), ('Time', ''), ('Info', 'Unconfirmed'), ('Location', '')]), OrderedDict([('Subject', 'Hogle Zoo?'), ('Date', 44167), ('Time', ''), ('Info', 'Unconfirmed'), ('Location', '')]), OrderedDict([('Subject', 'Hogle Zoo?'), ('Date', 44174), ('Time', ''), ('Info', 'Unconfirmed'), ('Location', '')]), OrderedDict([('Subject', 'Hogle Zoo?'), ('Date', 44181), ('Time', ''), ('Info', 'Unconfirmed'), ('Location', '')]), OrderedDict([('Subject', 'Hogle Zoo?'), ('Date', 44188), ('Time', ''), ('Info', 'Unconfirmed'), ('Location', '')]), OrderedDict([('Subject', 'Thanksgiving Point'), ('Date', 'Always'), ('Time', ''), ('Info', '$2 per person, up to six people, with EBT'), ('Location', '')])]
y = [OrderedDict([('Subject', 'Tracy Aviary'), ('Date', 43501), ('Time', ''), ('Info', ''), ('Location', '')]), OrderedDict([('Subject', 'Utah Museum of Fine Arts'), ('Date', 'Always'), ('Time', ''), ('Info', 'Free with EBT'), ('Location', '')]), OrderedDict([('Subject', 'Natural History Museum of Utah (GET TICKETS!)'), ('Date', 43893), ('Time', 0.4166666666666667), ('Info', 'https://nhmu.utah.edu/free-days-nhmu'), ('Location', '301 Wakara Way, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Natural History Museum of Utah (GET TICKETS!)'), ('Date', 43984), ('Time', 0.4166666666666667), ('Info', 'https://nhmu.utah.edu/free-days-nhmu'), ('Location', '301 Wakara Way, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Natural History Museum of Utah (GET TICKETS!)'), ('Date', 44075), ('Time', 0.4166666666666667), ('Info', 'https://nhmu.utah.edu/free-days-nhmu'), ('Location', '301 Wakara Way, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Butte Garden'), ('Date', 43945), ('Time', ''), ('Info', ''), ('Location', '300 Wakara Way, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Butte Garden'), ('Date', 44036), ('Time', ''), ('Info', ''), ('Location', '300 Wakara Way, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Butte Garden'), ('Date', 44081), ('Time', ''), ('Info', ''), ('Location', '300 Wakara Way, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Butte Garden'), ('Date', 44109), ('Time', ''), ('Info', ''), ('Location', '300 Wakara Way, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Butte Garden'), ('Date', 44170), ('Time', ''), ('Info', ''), ('Location', '300 Wakara Way, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Butte Garden'), ('Date', 44171), ('Time', ''), ('Info', ''), ('Location', '300 Wakara Way, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Clark Planetarium'), ('Date', 'Always'), ('Time', ''), ('Info', 'Always Free; 110 400 W, Salt Lake City, UT'), ('Location', '')]), OrderedDict([('Subject', 'Free National Parks'), ('Date', 43850), ('Time', ''), ('Info', ''), ('Location', '')]), OrderedDict([('Subject', 'Free National Parks'), ('Date', 43939), ('Time', ''), ('Info', ''), ('Location', '')]), OrderedDict([('Subject', 'Free National Parks'), ('Date', 44068), ('Time', ''), ('Info', ''), ('Location', '')]), OrderedDict([('Subject', 'Free National Parks'), ('Date', 44100), ('Time', ''), ('Info', ''), ('Location', '')]), OrderedDict([('Subject', 'Free National Parks'), ('Date', 44146), ('Time', ''), ('Info', ''), ('Location', '')]), OrderedDict([('Subject', 'Hill Aerospace Museum'), ('Date', 'Always'), ('Time', ''), ('Info', 'Always Free; (Ogden) 7961 Wardleigh Rd, Hill AFB, UT 84056'), ('Location', '')]), OrderedDict([('Subject', 'Scales and Tails'), ('Date', 'Always'), ('Time', ''), ('Info', 'Free with POAP'), ('Location', '')]), OrderedDict([('Subject', 'Hogle Zoo?'), ('Date', 44139), ('Time', ''), ('Info', 'Unconfirmed'), ('Location', '2600 Sunnyside Ave S, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Hogle Zoo?'), ('Date', 44146), ('Time', ''), ('Info', 'Unconfirmed'), ('Location', '2600 Sunnyside Ave S, Salt Lake City, UT 84108')]), OrderedDict([('Subject', 'Hogle Zoo?'), ('Date', 44153), ('Time', ''), ('Info', 'Unconfirmed'), ('Location', '')]), OrderedDict([('Subject', 'Hogle Zoo?'), ('Date', 44160), ('Time', ''), ('Info', 'Unconfirmed'), ('Location', '')]), OrderedDict([('Subject', 'Hogle Zoo?'), ('Date', 44167), ('Time', ''), ('Info', 'Unconfirmed'), ('Location', '')]), OrderedDict([('Subject', 'Hogle Zoo?'), ('Date', 44174), ('Time', ''), ('Info', 'Unconfirmed'), ('Location', '')]), OrderedDict([('Subject', 'Hogle Zoo?'), ('Date', 44181), ('Time', ''), ('Info', 'Unconfirmed'), ('Location', '')]), OrderedDict([('Subject', 'Hogle Zoo?'), ('Date', 44188), ('Time', ''), ('Info', 'Unconfirmed'), ('Location', '')]), OrderedDict([('Subject', 'Thanksgiving Point'), ('Date', 'Always'), ('Time', ''), ('Info', '$2 per person, up to six people, with EBT'), ('Location', '')])]

def different_from_old(line, old_calendar):
    return old_calendar and all(line != old_line for old_line in old_calendar)

different_from_old(x[0], y)

False