In [1]:
%reload_ext autoreload
%autoreload 2
import json
import sys
sys.path.append("../..")
from pathlib import Path
from data_processing.online_coordinate_data.create_dataset import *
import matplotlib.pyplot as plt

import numpy as np
from hwr_utils.stroke_plotting import draw_from_gt

def distance_metric(x,y):
    """ Euclidean distance metric between x and x-1; first item in stroke has distance of epsilon
    Args:
        x: array-like
        y: array-like

    Returns:

    """

    output = np.zeros(x.size)
    output[1:] = ((x[:-1] - x[1:]) ** 2 + (y[:-1] - y[1:]) ** 2) ** (1 / 2)
    #output[0] = 1e-8
    return output

def reparameterize_as_func_of_distance(x,y,start_strokes):
    """ Instead of time, re-parameterize entire sequence as distance travelled

    Args:
        x: List of x's
        y: List of y's
        start_strokes: List of start stroke identifiers [1,0,0,1...

    Returns:
        distance travelled for each complete stroke
    """
    if isinstance(x, list):
        x=np.array(x)
    if isinstance(y, list):
        y=np.array(y)

    distances = distance_metric(x,y)
    distances[start_strokes==1] = 0
    cum_sum = np.cumsum(distances) # distance is 0 at first point; keeps length the same
    return cum_sum


x = np.array(range(0,10))
y = x.copy()
start_strokes = np.zeros(10)
start_strokes[0] =1
start_strokes[5] =1
start_strokes[8] =1

distances = distance_metric(x,y)
print(distances)
print(distances[start_strokes==1])
distances[start_strokes==1] = 0
print(distances)
    
reparameterize_as_func_of_distance(x,y,start_strokes)


[0.         1.41421356 1.41421356 1.41421356 1.41421356 1.41421356
 1.41421356 1.41421356 1.41421356 1.41421356]
[0.         1.41421356 1.41421356]
[0.         1.41421356 1.41421356 1.41421356 1.41421356 0.
 1.41421356 1.41421356 0.         1.41421356]


array([0.        , 1.41421356, 2.82842712, 4.24264069, 5.65685425,
       5.65685425, 7.07106781, 8.48528137, 8.48528137, 9.89949494])

In [ ]:
start_strokes==1

In [ ]:
def get_all_substrokes(stroke_dict, desired_num_of_strokes=3):
    """

    Args:
        stroke_dict: ['x', 'y', 't', 'start_times', 'x_to_y', 'start_strokes', 'raw', 'tmin', 'tmax', 'trange']
        desired_num_of_strokes:

    Returns:

    """
    if desired_num_of_strokes is None:
        yield stroke_dict
        return

    start_args = np.where(stroke_dict.start_strokes==1)[0] # returns an "array" of the list, just take first index
    start_args = np.append(start_args, None) # last start arg should be the end of the sequence

    # If fewer strokes, just return the whole thing
    if start_args.shape[0] <= desired_num_of_strokes:
        return stroke_dict

    for stroke_number in range(start_args.shape[0] - desired_num_of_strokes): # remember, last start_stroke is really the end stroke
        start_idx = start_args[stroke_number]
        end_idx = start_args[stroke_number + desired_num_of_strokes]

        t = stroke_dict.t[start_idx:end_idx].copy()
        x = stroke_dict.x[start_idx:end_idx].copy()
        y = stroke_dict.y[start_idx:end_idx].copy()
        raw = stroke_dict.raw[stroke_number:stroke_number + desired_num_of_strokes]
        start_strokes = stroke_dict.start_strokes[start_idx:end_idx]
        start_times = stroke_dict.start_times[stroke_number:stroke_number + desired_num_of_strokes + 1].copy()

        y, scale_param = normalize(y)
        x, scale_param = normalize(x, scale_param)
        x_to_y = np.max(x) / np.max(y)

        start_time = t[0]
        t -= start_time
        start_times -= start_time
        output = edict({"x": x,
                        "y": y,
                        "t": t,
                        "start_times": start_times,
                        "start_strokes": start_strokes,
                        "x_to_y":x_to_y,
                        "raw":raw})
        
        assert start_times[0]==t[0]
        yield output




# "../../data/online_coordinate_data/3_stroke_16_v2/train_online_coords.json"
# FROM ORIGINAL XMLs
json_path="../../data/prepare_online_data/online_augmentation.json"
original_img_folder = "prepare_online_data/lineImages"
xml_root = "../../data/prepare_online_data/line-level-xml/lineStrokes"

# # FROM GENERATED XMLs
# json_path="../../data/online_coordinate_data/3_stroke_16_v2/train_online_coords.json"
# original_img_folder = "online_coordinate_data/3_stroke_16_v2/images"
# xml_root = "../../data/prepare_online_data/line-level-xml/lineStrokes"


with open(json_path) as f:
    output_dict = json.load(f)
print(output_dict[0].keys())

for i in output_dict:
    if "a01-001w-08" in i["image_path"]:
        instance = i
        print(i["image_path"])

rel_path = Path(instance["image_path"]).relative_to(original_img_folder).with_suffix(".xml")
xml_path = xml_root / rel_path
print(xml_path)


stroke_list, _ = read_stroke_xml(xml_path)
print(stroke_list[1])
stroke_dict = prep_stroke_dict(stroke_list, time_interval=0, scale_time_distance=True) # list of dictionaries, 1 per file


xx = list(get_all_substrokes(stroke_dict))
xx = [stroke_dict]
for x in xx:
    plt.scatter(x["x"], x["y"])
    plt.plot(x["x"], x["y"])
    plt.show()
print(x)

In [ ]:
json_path = "../../data/online_coordinate_data/3_stroke_16_v2/train_online_coords.json"

with open(json_path) as f:
    output_dict = json.load(f)

for x in output_dict:
    print(x.keys())
    plt.scatter(x["gt"][0], x["gt"][1])
    plt.plot(x["gt"][0], x["gt"][1])
    plt.show()
    stop


In [ ]:
json_path = "../../data/online_coordinate_data/3_stroke_64_v2/train_online_coords.json"

with open(json_path) as f:
    output_dict = json.load(f)

for x in output_dict:
    if "a01-001w-08" in x["image_path"]:
        print(x.keys())
        plt.scatter(x["x"], x["y"])
        plt.plot(x["x"], x["y"])
        plt.show()


In [ ]:
json_path = "../../data/online_coordinate_data/8_stroke_vSmall_16/train_online_coords.json"

with open(json_path) as f:
    output_dict = json.load(f)

    
for x in output_dict:
    #print(x["full_img_path"])
    if "a01-001w-08" in x["full_img_path"]:
        x = prep_stroke_dict(x["raw"], time_interval=0, scale_time_distance=True) # list of dictionaries, 1 per file
        plt.scatter(x["x"], x["y"])
        plt.plot(x["x"], x["y"])
        plt.axis('off')
        plt.axis('square')
        plt.show()
        print(x.keys())
        
# dict_keys(['full_img_path', 'xml_path', 'image_path', 'dataset', 'x', 'y', 't', 'start_times', 'start_strokes', 'x_to_y', 'raw', 'shape']) 

In [64]:
json_path = "../../data/online_coordinate_data/8_stroke_vSmall_16/train_online_coords.json"

parameter = "t"
with open(json_path) as f:
    output_dict = json.load(f)
  
i = 0
for x in output_dict:
    #print(x["full_img_path"])
    if "a01-001w-08" in x["full_img_path"]:
        i += 1
        if i ==20:
            break

# Original Processing
print(x.keys())
gt = np.array([x["x"],x["y"],x["start_strokes"]]).transpose(1,0)
draw_from_gt(gt, show=True, use_stroke_number=False)

output = prep_stroke_dict(x["raw"], time_interval=0, scale_time_distance=True) # list of dictionaries, 1 per file
print(output.keys())

# After prepping
gt = np.array([output["x"],output["y"],output["start_strokes"]]).transpose(1,0)
draw_from_gt(gt, show=True, use_stroke_number=False)

# After sampling
x_func, y_func = stroke_recovery.create_functions_from_strokes(output, parameter=parameter) # can be d if the function should be a function of distance
starts = output.start_times if parameter=="t" else output.start_distances
x, y, is_start_stroke = stroke_recovery.sample(x_func, y_func, starts, 1000, noise=None)

# plt.scatter(x,y)
# plt.plot(x,y)
gt = np.array([x,y,is_start_stroke]).transpose([1,0])
draw_from_gt(gt, show=True, use_stroke_number=False)

dict_keys(['full_img_path', 'xml_path', 'image_path', 'dataset', 'x', 'y', 't', 'start_times', 'start_strokes', 'x_to_y', 'raw', 'shape'])
dict_keys(['x', 'y', 't', 'd', 'start_times', 'start_distances', 'x_to_y', 'start_strokes', 'raw', 'tmin', 'tmax', 'trange', 'drange'])


array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255],
       [255,   0,   0, ..., 255, 255, 255]], dtype=uint8)

In [49]:
from hwr_utils.stroke_recovery import *

background = tuple([255])

img = Image.new("L", (50, 50), background)
draw = ImageDraw.Draw(img)
color = 0
linewidth = 2
pil_format = [np.array([[10,20,30],[10,20,30]]), np.array([[15],[15]])]

for line in pil_format:
    if line.size > 2:
        line = [tuple(x) for x in line.flatten().reshape(-1,2).tolist()]
        draw.line(line, fill=color, width=linewidth, joint='curve')
        draw.ellipse((15, 15, 16, 16), fill = 'blue', outline ='blue')

img.show()

In [63]:
from hwr_utils.stroke_recovery import *

background = tuple([255])

img = Image.new("L", (50, 50), background)
draw = ImageDraw.Draw(img)
color = 0
linewidth = 3
pil_format = [np.array([[10,20,30],[10,20,30]]), np.array([[15],[15]])]

for line in pil_format:
    if line.size > 2:
        line = [tuple(x) for x in line.flatten().reshape(-1,2).tolist()]
        draw.line(line, fill=color, width=linewidth, joint='curve')
    elif line.size == 2:
        line1 = line - linewidth/2
        line2 = line + linewidth/2
        line = np.r_[line1, line2].flatten().tolist()
        draw.ellipse(line, fill = 'black', outline ='black')

# line = (20,5,6,19)
# draw.ellipse(line, fill = 'blue', outline ='blue')
# draw.ellipse((15, 15, 16, 16), fill = 'blue', outline ='blue')


img.show()

In [73]:
json_path = "../../data/online_coordinate_data/8_stroke_vSmall_16/train_online_coords.json"

parameter = "d"
with open(json_path) as f:
    output_dict = json.load(f)
  
i = 0
for x in output_dict:
    #print(x["full_img_path"])
    if "a01-001w-08" in x["full_img_path"]:
        i += 1
        if i ==20:
            break

# After sampling
x_func, y_func = stroke_recovery.create_functions_from_strokes(output, parameter=parameter) # can be d if the function should be a function of distance
starts = output.start_times if parameter=="t" else output.start_distances
x, y, is_start_stroke = stroke_recovery.sample(x_func, y_func, starts, 1000, noise=None)

gt = np.array([x,y,is_start_stroke]).transpose([1,0])
draw_from_gt(gt, show=True, use_stroke_number=False, plot_points=True)

[11.577181208053691, 22.016778523489933, 12.577181208053691, 23.016778523489933]
[10.977218559113728, 22.016778523489933, 11.977218559113728, 23.016778523489933]
[10.377255910173766, 22.016778523489933, 11.377255910173766, 23.016778523489933]
[9.823477797714466, 21.83854657665718, 10.823477797714466, 22.83854657665718]
[9.299016082742448, 21.54717895722828, 10.299016082742448, 22.54717895722828]
[8.774554367770428, 21.25581133779938, 9.774554367770428, 22.25581133779938]
[8.254935340904826, 20.957074681439437, 9.254935340904826, 21.957074681439437]
[7.779390552788271, 20.591270998272858, 8.779390552788271, 21.591270998272858]
[7.303845764671716, 20.225467315106275, 8.303845764671717, 21.225467315106275]
[6.82830097655516, 19.859663631939693, 7.82830097655516, 20.859663631939693]
[6.352756188438605, 19.493859948773114, 7.352756188438605, 20.493859948773114]
[5.87721140032205, 19.12805626560653, 6.87721140032205, 20.12805626560653]
[5.413755869921431, 18.74752296336246, 6.413755869921431

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[  0,   0, 255],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [  0,   0, 255],
        [  0,   0,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [  0,   0, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]